fmP0JkMZ: Add GetBasketRecommendations request
LoopFiftyFour/PHP-Connector pull request #19
Opened 2021-11-25 09:42 UTC by lukethenuke

2021-11-25 12:43 UTC, joelwkall reviewed
Would like some code examples here. 

Also @loop54-christoffer can you take a look as well? I'm out of my depth here.

2021-11-25 12:43 UTC, joelwkall commented on lib/OpenAPI/Api/UserInitiatedApi.php
> +    /**
This is all generated, right?

2021-11-25 12:43 UTC, joelwkall commented on lib/OpenAPI/Model/GetBasketRecommendationsRequest.php
> +<?php
And this?

2021-11-25 12:43 UTC, joelwkall commented on lib/OpenAPI/Model/GetBasketRecommendationsResponse.php
> +<?php
And this?

2021-11-25 12:50 UTC, lukethenuke commented on lib/OpenAPI/Api/UserInitiatedApi.php
> +    /**
These are the autogenerated ones:
```
lib/OpenAPI/Api/UserInitiatedApi.php
lib/OpenAPI/Model/GetBasketRecommendationsRequest.php
lib/OpenAPI/Model/GetBasketRecommendationsResponse.php
test/OpenAPI/Api/UserInitiatedApiTest.php
test/OpenAPI/Model/GetBasketRecommendationsRequestTest.php
test/OpenAPI/Model/GetBasketRecommendationsResponseTest.php
```

2021-11-26 11:39 UTC, loop54-christoffer commented on examples/Simple.php
> +    // echo '--------------------------------------------' . PHP_EOL;
Should these comments be committed?

2021-11-26 11:43 UTC, loop54-christoffer commented on test/OpenAPI/Api/UserInitiatedApiTest.php
> + * @package  Loop54\API\OpenAPI
Hm. Is this relative path not a problem?

2021-11-26 11:44 UTC, loop54-christoffer commented on test/resources/getBasketRecommendations_response_plain.json
> +{
Is this an actual response copy-pasted from a real engine?

2021-11-26 11:44 UTC, loop54-christoffer requested changes
Commented out test cases, namespace change, and question on the canned test response are the three things I can see that block an approval from my end.

2021-11-26 13:23 UTC, lukethenuke commented on examples/Simple.php
> +    // echo '--------------------------------------------' . PHP_EOL;
Oops, they should not. Good catch!

2021-11-26 13:25 UTC, lukethenuke commented on test/resources/getBasketRecommendations_response_plain.json
> +{
It's an copy from the getRelatedEntities_response_plain.json which has the same structure.

2021-11-26 13:26 UTC, lukethenuke commented on test/OpenAPI/Api/UserInitiatedApiTest.php
> + * @package  Loop54\API\OpenAPI
I have not seen any issue while testing. That is what the openapi generator is generating for me. It looks like it's mixed in our project between slash and unslashed paths.

2021-11-26 13:50 UTC, loop54-christoffer commented on test/resources/getBasketRecommendations_response_plain.json
> +{
Ah, that makes sense.

2021-11-26 13:52 UTC, loop54-christoffer commented on test/OpenAPI/Api/UserInitiatedApiTest.php
> + * @package  Loop54\API\OpenAPI
...can you make it generate an absolute path? Not because I think that's the right thing to do, only because I'm not at all sure about what the right thing to do is so I'm erring on the side of not changing things. How sure are you that a relative path is the right thing to do?

2021-11-30 13:07 UTC, lukethenuke commented on test/OpenAPI/Api/UserInitiatedApiTest.php
> + * @package  Loop54\API\OpenAPI
I can, but then the namespace would be `namespace \Loop54\API\OpenAPI;` which to me looked like more impactfull change then a comment change.
I don't know what is correct or not, so if you do please help me out :see_no_evil:

2021-12-01 14:53 UTC, loop54-christoffer commented on test/OpenAPI/Api/UserInitiatedApiTest.php
> + * @package  Loop54\API\OpenAPI
Aha. I missed that. Well, then I think the way you've done it is good.

2021-12-01 14:54 UTC, loop54-christoffer approved these changes

2021-12-06 16:14 UTC, merged